/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "ocelot.h"
#include "main.h"

/* Header for class it_unisa_ocelot_simulator_CBridge */

#ifndef _Included_it_unisa_ocelot_simulator_CBridge
#define _Included_it_unisa_ocelot_simulator_CBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_unisa_ocelot_simulator_CBridge
 * Method:    getEvents
 * Signature: (Lit/unisa/ocelot/simulator/EventsHandler;)V
 */
JNIEXPORT void JNICALL Java_it_unisa_ocelot_simulator_CBridge_getEvents(JNIEnv *, jobject, jobject, jobjectArray);
jint _f_ocelot_intval(JNIEnv*, jobject);
jdouble _f_ocelot_doubleval(JNIEnv*, jobject);

#define OCELOT_ARG(i) (*env)->GetObjectArrayElement(env, arguments, i)
#define OCELOT_int(object) _f_ocelot_intval(env, object)
#define OCELOT_double(object) _f_ocelot_doubleval(env, object)

#ifdef __cplusplus
}
#endif
#endif
