/** DO NOT EDIT. THIS FILE IS AUTOMATICALLY GENERATED BY THE BUILDER **/
#ifndef _Included_OcelotPointers
#define _Included_OcelotPointers
#define OCELOT_ARRAYS_SIZE 1
typedef double _t_ocelot_array[OCELOT_ARRAYS_SIZE];
#endif
